name: my-binder-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - spacy
  - geoparser
  - accelerate
  - appdirs
  - datasets
  - haversine
  - numpy
  - pandas
  - requests
  - tqdm
  - pytorch  # torch package from conda is called pytorch
  - pip:
      - sentence-transformers  # installed via pip